version: '3.9'

services:
  api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile.dev
    container_name: vaulted_api
    ports:
      - '3000:3000'
    volumes:
      - ./apps/api:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
      PORT: 3000
      APP_URL: http://192.168.18.6:3000
      MONGODB_URI: mongodb://mongodb:27017/vaulted
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: vaulted
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: 24h
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
      JWT_REFRESH_EXPIRES_IN: 7d
    depends_on:
      mongodb:
        condition: service_healthy
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - vaulted_network
    restart: unless-stopped

  mongodb:
    image: mongo:7.0
    container_name: vaulted_mongodb
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: ['CMD', 'mongosh', '--eval', 'db.adminCommand("ping")']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - vaulted_network
    restart: unless-stopped

  postgres:
    image: postgres:16-alpine
    container_name: vaulted_postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: vaulted
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d vaulted']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - vaulted_network
    restart: unless-stopped

  redis:
    image: redis:7.2-alpine
    container_name: vaulted_redis
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    command: redis-server --requirepass ${REDIS_PASSWORD} --appendonly yes
    healthcheck:
      test: ['CMD', 'redis-cli', '-a', '${REDIS_PASSWORD}', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - vaulted_network
    restart: unless-stopped

volumes:
  mongodb_data:
  postgres_data:
  redis_data:

networks:
  vaulted_network:
    driver: bridge
